channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.7.5
  - nltk==3.4.5
  - pytorch==1.8.1
  - pyyaml==5.3.1
  - numpy==1.20.3
  - pika==1.2.0
  - git
  - pip
  - pip:
      - git+https://github.com/pytorch/fairseq.git@d6855baec88f99ac776962027b91d404fe917eea
      - sentencepiece